import {useEffect,useState} from 'react';
export type LocalModel={id:string;name:string;kind:string;license:string;url:string;preset:string;state:string;ready:boolean;supported:boolean;installable:boolean;progress:number;download_bytes:number|null;installed_bytes:number|null;guidance:string;error?:string;gated?:boolean;voices?:string[]};
const size=(n:number|null)=>n===null?'Not yet pinned':`${(n/1024**3).toFixed(2)} GiB`;
export function LocalModels(){
 const [models,setModels]=useState<LocalModel[]>([]),[hardware,setHardware]=useState(''),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false);
 async function refresh(){const response=await fetch('/api/admin/local-models');if(!response.ok)throw Error('Could not load local models');const data=await response.json();setModels(data.models);setHardware(data.hardware.gpus.map((g:{name:string;total_mib:number;free_mib:number})=>`${g.name}: ${g.free_mib} / ${g.total_mib} MiB free`).join(' · ')+' '+data.hardware.guidance);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(timer);},[]);
 async function action(id:string,action:string){setBusy(true);setError('');try{const response=await fetch(`/api/admin/local-models/${id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accept_license:accepted})});const data=await response.json();if(!response.ok)throw Error(data.detail);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="admin-section"><h2>Local models</h2><p>Generate media on this workstation with no provider charges. Install downloads the selected model and its isolated Windows runtime. Installed models work offline.</p><p className="note">{hardware}</p><p>Keep the EXE and ScriptStudioNative folder together. Downloads, models, caches and scratch files stay inside that folder. Each install reserves expanded space plus 2 GiB for working files.</p>{error&&<p role="alert" className="error">{error}</p>}{models.map(m=><article className="credential" key={m.id}><h3>{m.name} · {m.kind}</h3><p>{m.preset}</p><p><a href={m.url} target="_blank" rel="noreferrer">{m.license}</a></p><p>Download: {size(m.download_bytes)} · Expanded runtime allowance: {size(m.installed_bytes)}</p><p role="status">{m.ready?'Ready':m.state.replaceAll('_',' ')} · {m.guidance}</p>{['downloading','installing','verifying'].includes(m.state)&&<progress max="1" value={m.progress||0}/>}<p>{m.error}</p>{m.gated&&<><p>Accept the upstream license and commercial conditions on Hugging Face, then save an authorized Hugging Face token below. The token is encrypted and never returned.</p><label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>I accepted the upstream license and applicable commercial-use conditions</label></>}<div className="row">{(['install','cancel','resume','verify','uninstall'] as const).map(a=><button key={a} disabled={busy||(a==='install'&&(!m.supported||!m.installable||(m.gated&&!accepted)))} onClick={()=>void action(m.id,a)}>{a[0].toUpperCase()+a.slice(1)}</button>)}</div></article>)}</section>;
}
